### ISSUE TITLE
bypass and ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION

### ISSUE THREAD

**Issue by spikedrba** [e2guardian/e2guardian#181]
Hi,

per convo on ML, I'm opening an issue regarding the multiple location header bug. I've not had the time to double check, but this may be a general problem with bypass and 302 redirects.

Repro:
* ban flickr.com
* enable bypass
* use bypass on denied page
* observe the error

A wireshark dump reveals indeed the multiple location headers.
```
GET /?GBYPASS=F8750859951F27BE35D831A7A2F30F1A1488341408 HTTP/1.1
Host: www.flickr.com
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Referer: http://www.flickr.com/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

HTTP/1.0 302 Redirect
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Served-By: pprd1-node311-lh1.manhattan.gq1.yahoo.com
X-Instance: flickr.v1.production.manhattan.gq1.yahoo.com
Cache-Control: no-cache, max-age=0, must-revalidate, no-store
Pragma: no-cache
X-Request-Id: f414b1df
Location: https://www.flickr.com/ <----- THIS ONE
Vary: Accept
Content-Type: text/html; charset=utf-8
Content-Length: 0
Date: Wed, 01 Mar 2017 04:05:11 GMT
Age: 0
Server: ATS
X-Cache: MISS from srv-gw
X-Cache-Lookup: MISS from srv-gw:3128
Via: http/1.1 fts106.flickr.gq1.yahoo.com (ApacheTrafficServer [cMs f ]), https/1.1 e10.ycpi.laa.yahoo.com (ApacheTrafficServer [cMsSf ]), 1.1 srv-gw (squid/3.5.12)
Connection: keep-alive
Set-Cookie: GBYPASS=AB7F3E0177E20C1687D0E37CC5632A241488341408; path=/; domain=.flickr.com
Location: http://www.flickr.com <------- THIS OTHER ONE
```

A connection without going through the content filter results in a correct redirect to the https version.

thanks,

Spike

**Comment by fredbcode** [comment]
Hi I pushed a change can you make a try with the dev branch ? (with wireshark please) 
Be carreful I'm working about NTLM, there are certainly some bugs about ...

**Comment by fredbcode** [comment]
No news ?

**Comment by spikedrba** [comment]
I'm stuck with a migration to a loadbalanced gw, I should get to this by thursday, bear with me, thank you

**Comment by spikedrba** [comment]
ok, I got to it and nope, that did not fix it. This is a capture from flickr.com -> www.flickr.com , ie another redirect, nothing to do with https, it's definitely 302 related:

<pre>
HTTP/1.0 302 Redirect
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Served-By: pprd1-node99-lh1.manhattan.bf1.yahoo.com
X-Instance: flickr.v1.production.manhattan.bf1.yahoo.com
Location: http://www.flickr.com/    <--------------------------------- DUP
Vary: Accept
Content-Type: text/html; charset=utf-8
Content-Length: 0
Date: Wed, 08 Mar 2017 00:22:45 GMT
Age: 0
Server: ATS
X-Cache: MISS from lxc-x1
X-Cache-Lookup: MISS from lxc-x1:3128
Via: http/1.1 fts123.flickr.bf1.yahoo.com (ApacheTrafficServer [cMsSf ]), 1.1 lxc-x1 (squid/3.5.12)
Connection: keep-alive
Set-Cookie: GBYPASS=36D5B183E3280CC9A8B236F4DC9F21F51488932774; path=/; domain=.flickr.com
Location: http://flickr.com <--------------- DUP
</pre>

Pretty sure I'm testing the right code:
root@lxc-x1:~/e2guardian# git branch
* develop
  master

I've also modified _configure.ac_ to change the version number to be sure: AC_INIT(e2guardian, 3.5.1d)

and indeed:
root@lxc-x1:~/e2guardian# e2guardian --version
e2guardian 3.5.1d

thanks,

Spike

**Comment by fredbcode** [comment]
Ok, I pushed a debug version please "pull"

can you try with -N (e2guardian -N) and tell me which message you have with flickr.com

Can you provide your configuration to reproduce ?

**Comment by spikedrba** [comment]
will test some time tonight/tomorrow. Btw couldn't see the changes at first because the commit is tagged #176 , guess the issue could indeed be related.

About repro, from stock configs, I simply set bypass = 300 , add a custom.html page to get the bypass button and put flickr.com in lists/bannedsiteslist . that's it.

**Comment by sonertari** [comment]
I can confirm that the issue exists with most of the sites I have tried. But I have noticed something interesting: When I try to access, for example, bc.edu or nzherald.co.nz, the same problem happens (ERR_RESPONSE_HEADERS_MULTIPLE_LOCATION). However, if I try www.bc.edu and www.nzherald.co.nz, the problem goes away. Notice that I just place www subdomain in the front, that's all. But interestingly this does not help with flickr.com or slashdot.com.

spikedrba, can you also try bc.edu and nzherald.co.nz, without www subdomain first, then with it to see if the problem goes away? (without using fredbcode's debug version of course)

Btw, I am still using 3.4.0.3, but I have tried Dansguardian 2.12.0.3 and 2.10.1.1 too. The same issue exists with them. However, I was using 2.10.1.1 back in 2009, and I don't recall any such problems. So I guess today's browsers are more sensitive to such protocol violations?

I will try fredbcode's debug version asap too.

**Comment by sonertari** [comment]
I have just tried the develop branch for #176. And I am sorry to report that it does not fix the issue here. Everything is the same.

Please note again that adding www subdomain in front works around this problem for some domains. This may give us a clue on whereabouts of this issue in the code. Any ideas? I am planning to look into this issue myself too.

As it is, bypass feature of e2guardian does not work for me. And I tend to think that we should never have any duplicate location fields in the headers anymore (it was probably ok in the past, with the browsers of those times).

**Comment by sonertari** [comment]
Btw, I forgot to mention, I always get the following message with -N:
Fred returncode = 0
even after working around the issue with the www subdomain.

**Comment by fredbcode** [comment]
Yes I guess this issues is caused by 302 code 
Look: When you are using bc.edu there is a 302 code (redirection) to www.bc.edu 

I will investigate

**Comment by fredbcode** [comment]
Sorry I guess there is something I misunderstand 
- I set bypass = 300 
- I added a link to my page </b><font color="red">&nbsp;<b><a href="-BYPASS-">-URL-</a></b>&nbsp;<br>
- I added a domain to my blacklist

I'm seeing my webpage and when I try the button http://www.toto.com/?GBYPASS=CAA28D9B9B7C2A3D9E106D67847BB1281489045974
My request is also denied  ...

I certainly missed something

**Comment by sonertari** [comment]
I have just tried your first two Test fixes. I get a second access denied page for the www subdomain, but that's alright with me, although may be annoying for some users. Note that this does not solve flickr.com for me, because it redirects to secure http, which I don't have any configuration for, so that's fine too.

So, I think your fixes seem like working to me. (Note that I haven't tested yet your last patch adding 307 and 308 responses.)

**Comment by spikedrba** [comment]
hi, bit late to the party, thanks for jumping in @sonertari .

@fredbcode , latest develop branch works for me too, thank you so much for fixing this, I think it's a huge improvement since there's a lot of stuff issuing 302s these days.

Fwiw, like @sonertari said, I get a double access denied page, but I guess that makes sense since the cookie is to allow flickr.com, not www.flickr.com. You could argue that if I  bypass a domain all subdomains should also be allowed, but that's off topic for this ticket and maybe something for the future. I might submit another issue about that, altho you guys may disagree if that's the correct behavior, maybe a variable to configure.

gonna close this issue since I think the bug is fixed.

thanks,

Spike

**Comment by fredbcode** [comment]
Ok thanks but there are some little fixes to made
eg: All 302 requests are logged as "TRUSTED" I'm working on it

**Comment by fredbcode** [comment]
I think it's good now "302,301,307,308' requests are allowed and removed from log

**Comment by sonertari** [comment]
I have just tried. It's looking good to me. Thanks.

**Comment by fredbcode** [comment]
Fixed in 3.5.1
