### ISSUE TITLE
v3.1.2 will not load ca cert 

### ISSUE THREAD

**Issue by RaNd250** [e2guardian/e2guardian#50]
compiled 3.1.2 with 
./configure   --with-filedescriptors=1024 --with-proxygroup=dansguardian --with-proxyuser=dansguardian --enable-email --enable-sslextralists  --enable-orig-ip

v3.0.4 works great, however 3.1.2 could not start, with error "Couldn't open ca certificate", while
using the same config file on both

**Comment by fredbcode** [comment]
Please can you try the dev branch ? I think this bug is now fixed

**Comment by RaNd250** [comment]
It works now, but  i get version 3.0.4 in the src/Makefile (therefore in the e2guardian -v )

(I downloaded the master.zip from github )

**Comment by fredbcode** [comment]
You must use the ghitub command (git pull from develop), the .zip is only from the master branch
Something like this:
git clone https://github.com/e2guardian/e2guardian.git
cd e2guardian
git checkout -b develop origin/develop 
git pull

**Comment by RaNd250** [comment]
OK, build no. is now 3.3.0, but still get the same error, even with dgdebug...

**Comment by fredbcode** [comment]
Hum strange no problem for me, are you using this kind of values (on each group file) ?
Can you show your files ?

**Comment by fredbcode** [comment]
With ./configure --with-filedescriptors=1024 --with-proxygroup=dansguardian --with-proxyuser=dansguardian --enable-email --enable-sslextralists --enable-orig-ip SSLMITM should be disabled

**Comment by RaNd250** [comment]
Sorry for the last one, somehow the cert.key was renamed

**Comment by fredbcode** [comment]
Ok so the bug is fixed ?
Be carreful ssmitm is disabled in your case.

**Comment by fredbcode** [comment]
I mean cacertificatepath is useless

**Comment by RaNd250** [comment]
I have included --enable-sslmitm, but now i bumped on another issue.
I posted on Google groups to keep this clean.

https://groups.google.com/forum/#!topic/e2guardian/0FIFHkZlGmo

P.S Thanks for all the help :)

**Comment by fredbcode** [comment]
OK I let Philip answers to this question, and close this bug report
Glad to see that this bug is gone now
