### ISSUE TITLE
e2guardian 5.3.1 or 5.3.2 NAT slow down URL call extremly.

### ISSUE THREAD

**Issue by tachtler** [e2guardian/e2guardian#508]
Hi,

my setup **works fine with e2guardian 5.2.2**:
```
+----------------------+     +---------------------------+     +----------+
| Mobile Phone on WLAN | --> | Internal Firwall with NAT | --> | Internet |
+----------------------+     +---------------------------+     +----------+
                              NAT: 
                              ====
                              from: 192.168.0.0/24 Port 80
                              to  : 10.7.0.50 Port 8080
                              The NAT redirected fall into filter1 (group)
```
On e2guardian 5.3.1 when I type in the URL inside the Browser of the Mobile Phone **30 sec. to 60 sec. will nothing happen**. After that every new request will  be a little bit faster.

### Because of that behavior, I downgrade from e2guardian 5.3.1 to 5.2.2!

Please can you help and imagine where is the problem?

`/etc/e2guardian/lists/filtergrouplist`
```
# Filter Groups List file for DansGuardian
#
# Format is <user>=filter<1-9> where 1-9 are the groups
#
# Eg:
# daniel=filter2
#
# This file is only of use if you have more than 1 filter group
#
# Tachtler
klaus=filter2
petra=filter3
```

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Can you test with v5develop, please ?

**Comment by tachtler** [comment]
Hi  fredbcode,

I will try the v5develop as soon as possible, promise!

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi  fredbcode,

now I compiled the v5develop version, see below:
```
# e2guardian -v
e2guardian 5.3.2

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' 
'--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' 
'--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes'
'--enable-ntlm=yes' '--enable-pcre=yes' '--enable-sslmitm=yes'
'--enable-avastd=yes' '--enable-kavd=yes' 
'--enable-orig-ip' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
```

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi fredbcode,

now I could make some tests and the result is the same as with version 5.3.1:
#### unfortunately very slow.
```
+----------------------+     +---------------------------+     +----------+
| Mobile Phone on WLAN | --> | Internal Firwall with NAT | --> | Internet |
+----------------------+     +---------------------------+     +----------+
                              NAT: 
                              ====
                              from: 192.168.0.0/24 Port 80
                              to  : 10.7.0.50 Port 8080
                              The NAT redirected fall into filter1 (group)
```
Thank you!
Klaus.

**Comment by philipianpearce** [comment]
Your set-up seems different to usual.    
Why are you NATing port 80 on internal address range to port 8080 on another internal address?    Are you using explicit proxy (or WPAD) on your phone?    If not then the calls will be going direct to the internet sites and will not go through e2g at all.

**Comment by tachtler** [comment]
Hi philipianpearce,

as you can see I **NAT a whole network `192.168.0.0/24` Port `80`** to one **single address `10.7.0.50` Port `8080`** on which the `e2guardian` **is listening**.

This is necessary, because it is difficult to use a proxy on mobile phones. (yes, I know not impossible, but difficult)

```
+----------------------+     +---------------------------+     +----------+
| Mobile Phone on WLAN | --> | Internal Firwall with NAT | --> | Internet |
+----------------------+     +---------------------------+     +----------+
                              NAT: 
                              ====
                              from: 192.168.0.0/24 Port 80
                              to  : 10.7.0.50 Port 8080
                              The NAT redirected fall into filter1 (group)
```
All devices with that NAT rule and **NO login and registration** fall **automatically** into the `filter1` **group**.

Thank you!
Klaus.

**Comment by philipianpearce** [comment]
So you are NAT source IP 192.168.0.0/20 but destination port 80 to destination ip 10.7.0.50 destination port 8080??

If this is the case then the likely reason for the slow-down is that e2g is attempting to reverse-dns lookup the 10.7.0.50 and dns is timing out.

As a general rule you should not NAT transparent traffic before it reaches e2g.   It will work correctly without NAT if you make the system with e2g the default gateway for your WLAN and use iptables on the e2g system to redirect internet-bound traffic destination port 80 to port 8080.   This preserves the correct IPs and allows e2g to work correctly.   It is also the only way (with 443 redirected to 8443) to make transparent https work.

**Comment by tachtler** [comment]
Hi philipianpearce,

I'm not sure, if that is the problem, because **in version 5.2.2 it still works**. 

Second thing is, inside my network `reverse lookup for 10.7.0.50` is possible:
```
dig -x 10.7.0.50
; <<>> DiG 9.9.4-RedHat-9.9.4-73.el7_6 <<>> -x 10.7.0.50
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6382
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;50.0.7.10.in-addr.arpa.		IN	PTR

;; ANSWER SECTION:
50.0.7.10.in-addr.arpa.	10800	IN	PTR	vml70050.idmz.tachtler.net.

;; Query time: 1 msec
;; SERVER: 10.7.0.20#53(10.7.0.20)
;; WHEN: Tue Mar 05 14:10:27 CET 2019
;; MSG SIZE  rcvd: 91
```
I will **NOT make e2guardian to the default gateway**, because my NAT rule is IP-address specific, for example:
```
192.168.0.30:80 --> NAT --> 10.7.0.50:8080
192.168.0.10:80 --> no NAT --> use default gateway
```

Thank you for your patience!
Klaus.

**Comment by philipianpearce** [comment]
Hi Klaus, 

Is the slow-down just on phones, just on other devices or on all devices? 

What auth plug-in(s) are you using? And if more than one what order are they in? (There are some changes to auth code between v5.2.2 and v5.3.) 

Regards 
Philip 

----- Original Message -----

**Comment by tachtler** [comment]
Hi Philip,

actual on all devices which fall into the `filter1` group, **with the NAT construct** and **no auth**. On the other filter group with auth, the problem doesn't exists.

I have no extra plugins. I use the e2guardian with the default download manager (the only one at this time) and the clamd was embedded using the default configuration method.

p.s. If you want I can sent you my original configuration files?

Thank you!
Klaus

**Comment by philipianpearce** [comment]
Klaus, 

Yes please, Can you send e2guardian.conf, e2guardianf1.conf and f1.story? 

Regards 
Philip 
----- Original Message -----

**Comment by tachtler** [comment]
Hi Philip,

can I sent you the config files to an e-Mail address? philip.pearce@... I found ?

Thank you!
Klaus.

**Comment by tachtler** [comment]
Hi Philip,

e-Mail was sent to you!

Thank you!
Klaus.

**Comment by philipianpearce** [comment]
Hi Klaus,

Yes config files where helpful.

I have pushed possible fix to v5.3 branch

Would you try this?
Thanks
Philip

**Comment by tachtler** [comment]
Hi Philip,

yes of course, I will try this the next days.

Thank you!
Klaus.

**Comment by fredbcode** [comment]
Some news ?

**Comment by tachtler** [comment]
Hi  fredbcode,

will try it, but no time for it - but it's still on my todo list!

Thank you
Klaus.

**Comment by tachtler** [comment]
Hi fredbcode,

sunday morning, good time to test the latest e2guardian version 5.3.2, **BUT sorry the problem still exists**! 

### NOT working version:
```
e2guardian 5.3.2

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-pcre=yes' '--enable-sslmitm=yes' '--enable-avastd=yes' '--enable-kavd=yes' '--enable-orig-ip' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
```
**Open a browser on a mobile phone, type google.de as URL, I have to wait up till 90 sec.**
**Open a browser on a mobile phone, type www.tachtler.net (inside my network 10.7.0.90) as URL, I have to wait up till 90 sec too.**

### working version:
```
e2guardian 5.2.2

Built with:  '--prefix=/usr' '--enable-clamd=yes' '--with-proxyuser=e2guardian' '--with-proxygroup=e2guardian' '--sysconfdir=/etc' '--localstatedir=/var' '--enable-icap=yes' '--enable-commandline=yes' '--enable-email=yes' '--enable-ntlm=yes' '--enable-pcre=yes' '--enable-sslmitm=yes' '--enable-avastd=yes' '--enable-kavd=yes' '--enable-orig-ip' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig'
```
**Open a browser on a mobile phone, type google.de as URL, Google opens immediately**
**Open a browser on a mobile phone, type www.tachtler.net (inside my network 10.7.0.90) as URL, www.tachtler.net opens immediately**

Still with the same construct:
```
+----------------------+     +---------------------------+     +----------+
| Mobile Phone on WLAN | --> | Internal Firwall with NAT | --> | Internet |
+----------------------+     +---------------------------+     +----------+
                                                               +----------+
                                                           --> | INTRANET |
                                                               +----------+
                              NAT: 
                              ====
                              from: 192.168.0.0/24 Port 80
                              to  : 10.7.0.50 Port 8080
                              The NAT redirected fall into filter1 (group)
```



Thank you for your patience with me, because of the huge time gap for testing!
Klaus.

**Comment by tachtler** [comment]
Hi,

I've made some test, and I can show following behavior:

**Comment by tachtler** [comment]
Hi,

I've made some test, and I can show following behavior:
PC --> Proxy settings --> User & Password --> Fast (user specific filter group)
PC --> **NAT** rule --> **NO** User & Password --> **Slow** (default filter 1)

Thank you (sorry for the  close)
Klaus.
