### ISSUE TITLE
Continuous "out of memory" errors

### ISSUE THREAD

**Issue by jwc866** [e2guardian/e2guardian#588]
Hello:
I am new to E2Guardian and have a brand new setup.  I'm running it on a Raspberry Pi 4 with Raspian, that has 4 GB RAM, with a total of about 5 users in the environment.  Recently, after I enabled SSL support and set up MITM, it runs fine for several hours but eventually the e2guardian service runs in to an "out of memory" error and no longer can handle user requests.  I enabled dstats and at the time the out of memory occurs it shows:

time            httpw   busy    httpwQ  logQ    conx    conx/s  reqs    reqs/s  maxfd   LCcnt
1584755952      500     212     0       0       0       0       0       0       470     1

As you can see it's nowhere near the maximum httpworkers of 500 (set as default).  Also at the time it happens, the system still has 2 GB of RAM available:

MiB Mem :   3906.0 total,   2070.1 free,   1668.2 used,    167.7 buff/cache
MiB Swap:    100.0 total,    100.0 free,      0.0 used.   2106.9 avail Mem

What else can I check or how can I try to fix this?  It looks like I have plenty of resources but I can't figure out why the e2guardian service is getting this out of memory condition.

Thanks in advance.

**Comment by fredbcode** [comment]
Hello

Which version ? Compiled how ?

Le 21/03/2020 à 14:42, jwc866 a écrit :

**Comment by jwc866** [comment]
> Hello Which version ? Compiled how ? Le 21/03/2020 à 14:42, jwc866 a écrit :

It's version 5.3.1 using the default compiled version with Raspian.

**Comment by fredbcode** [comment]
Can you try with the v5.4 (dev version) here, please ? 
http://e2guardian.traceroot.fr/v5.4.dev/

**Comment by jwc866** [comment]
> Can you try with the v5.4 (dev version) here, please ? http://e2guardian.traceroot.fr/v5.4.dev/

Hello:  I tried the latest package:
http://e2guardian.traceroot.fr/v5.4.dev/e2raspbian_buster_v5.4.dev_20200325.deb

However with that package, the e2guardian service failed to start:

> -- The unit e2guardian.service has entered the 'failed' state with result 'exit-code'.
> Mar 25 19:23:06 webproxy e2guardian[15121]: Error loading auth plugins
> Mar 25 19:23:06 webproxy e2guardian[15121]: Error parsing the e2guardian.conf file or other e2guardian configuration files
> Mar 25 19:23:06 webproxy systemd[1]: Failed to start E2guardian Web filtering.
> -- Subject: A start job for unit e2guardian.service has failed
> -- Defined-By: systemd

I looked and all of the configuration files are in tact and correct permissions.  Still looking at it.

Thank you.

**Comment by fredbcode** [comment]
With 5.4 you must remove all config files, some path are changed now

I guess  with e2guardian -N you can find the missing file(s)

**Comment by Dalacor** [comment]
I can't remember where I saw it, but there is a known bug with 5.3.1 with running out of memory for mitm. I had the exact same problem and had to turn of mitm. This was fixed in either 5.3.2 or 53.3 I can't remember which.

I would recommend installing 5.3.4 (the latest stable version) as it comes with a completely brand new phraselist. Previous versions of E2g are using quite an old and outdated phrase list.

I would recommend removing the old version completely, installing the new version and then comparing the config files and changing whatever settings you want as there are a lot of changes in the config files especially (but not limited to) phrase lists.

5.4 is a development version so if you are new to E2G I would recommend 5.3.4 stable version instead.

**Comment by jwc866** [comment]
OK thank you very much, this is extremely helpful.  I see 5.3.4 is still in the unstable branch of Debian/Raspian.  I may wait for it to move over to the stable branch and then do the upgrade and then enable MITM.  Thank you for all of your help.

**Comment by fredbcode** [comment]
Closed for now, please feel to reopen if necessary

**Comment by jwc866** [comment]
> Hello:
> Can you try with the v5.4 (dev version) here, please ? http://e2guardian.traceroot.fr/v5.4.dev/

I have recently upgraded to 5.4 dev version, with this package:

http://e2guardian.traceroot.fr/v5.4.dev/e2raspbian_buster_v5.4.dev_20200407.deb

It seems this issue is still happening.  Things ran fine for about 24 hours, then I started to see the http workers increase in dstats.log until it reached the limit of 500.  The httpwQ then started to continually increase as well until I restarted the e2guardian service, then all returned back to normal.  At the time of the issue, free RAM was a little over 2 GB on the system.

Please let me know, if there's anything else I can check or try.  Thank you very much.

**Comment by Dalacor** [comment]
Your problem now is not the same as before. Before you had only half the httpworkers in use. Now you are running out of httpworkers! I suspect a website that you use is not letting the httpworker be released, so the httpworkers are increasing.

The end result is different, but I suspect that the cause is the same.

I had a similar issue with our email website and Edge! It was only when I whitelisted the email website that the problem went away.  You may need to enable loop detection to find the problem website.

https://github.com/e2guardian/e2guardian/issues/523

**Comment by jwc866** [comment]
Thank you.  OK, got it, so this is expected behavior.  Good to know and I will look in to further.  Thank you very much for the insight.

**Comment by Dalacor** [comment]
I would not say this is expected behaviour per se. More that I had a similar issue, but in my case the httpworkers jumped from around 50 to 500 within minutes. But that was probably down to the fact that the website was the email website!

I am not saying that your issue is related to this, but it just sounds like it may be. IT could be something to do with Raspberry for all I know.
